#!/usr/bin/env bash
# This script displays file names in the current directory after the first dash
for file in *
do
    if [ -f "$file" ] && [[ ! "$file" =~ ^\. ]]
    then
        echo "${file#*-}"
    fi
done
